import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  let arr = ["function", "test"];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Select <a href="/">RAISEC</a>
        </h1>
        <p className={styles.description}> </p>
        <div className={styles.grid}>
          <Link href="/RAISEC/Realistic" className={styles.card}>
            <a className={styles.card}>
              <h2>Realistic </h2>
            </a>
          </Link>

          <Link href="/RAISEC/Artistic" className={styles.card}>
            <a className={styles.card}>
              <h2>Artistic </h2>
            </a>
          </Link>

          <Link href="/RAISEC/Investigative" className={styles.card}>
            <a className={styles.card}>
              <h2>Investigative </h2>
            </a>
          </Link>

          <Link href="/RAISEC/Social" className={styles.card}>
            <a className={styles.card}>
              <h2>Social </h2>
            </a>
          </Link>

          <Link href="/RAISEC/Enterprising" className={styles.card}>
            <a className={styles.card}>
              <h2>Enterprising </h2>
            </a>
          </Link>

          <Link href="/RAISEC/Conventional" className={styles.card}>
            <a className={styles.card}>
              <h2>Conventional </h2>
            </a>
          </Link>
        </div>
        <h1>Welcome to HelloCareer!</h1>
        <br />
        <h1>We are a career education platform! The Problem:</h1>
        <h3 style={{ textAlign: "center" }}>
          Students are only exposed to mainstream careers like medicine and
          engineering thus they end up doing one of the two.They miss out
          learning on other careers that are made for them! <br />
          Our Aim: We aim to educate every student about various career
          opportunities available through a fun and interactive algorithm.{" "}
          <br />
          Our content pushes the user to imagine themselves doing that job. It
          is a 30 -60 min process where the outcome will be the users top most
          liked jobs! <br />
          <br />
          Please note We are NOT a career counseling platform, we don't suggest
          you take up the career you land on after the process, this is an
          experience which helps you understand the different options that are
          available and what your USP[unique selling proposition] is! If you
          know which category fits your characteristic, go ahead and select the
          option If you don't know, not a problem please take a RIASEC test
          <a
            style={{ color: "blue" }}
            href="https://www.onlinepersonalitytests.org/riasec/"
          >
            (https://www.onlinepersonalitytests.org/riasec/)
          </a>
        </h3>

        <hr />
        <h3>
          <h1>Realistic</h1> Realistic having or showing a sensible and practical idea of what can
          be achieved or expected.An example of realistic is a person who knows
          his own limitations and isn't going to expect to be an amazing opera
          singer when he can't even carry a tune.<h1> Investigative </h1> An investigative
          personality type tends to be analytical, intellectual and scholarly.
          They enjoy research, mathematical or scientific activities..
          <h1>Analytical</h1> An analytical person wants to gather and consider
          information at length before making a big decision. Even in small
          choices, they will tend to look to the numbers or data for guidance,
          rather than making an off-the-cuff choice.<h1> Social</h1> Individuals who are
          a social personality type are dedicated leaders, humanistic,
          responsible and supportive. They use feelings, words and ideas to work
          with people rather than physical activity to do things. They enjoy
          closeness, sharing, groups, unstructured activity and being in charge.
          <h1>Enterprise </h1>What is an enterprising person? These individuals like to
          work with people, influence, persuade, lead or manage for
          organizational goals or economic gain. An enterprising personality
          type is often a leader who is talented at organizing, persuading and
          managing. They enjoy money, power, status and being in charge.
          <h1>Conventional </h1>A conventional personality type likes to work with data
          and numbers, carry out tasks in detail and follow through on the
          instructions of others. They are quiet, careful, responsible, well
          organized and task oriented.
        </h3>
      </main>

      <footer className={styles.footer}>
        <a href="/" target="_blank" rel="noopener noreferrer">
          Hello Career{" "}
        </a>
      </footer>
    </div>
  );
}
